export const answers = [
  0, 3, 2, 0, 2, 1, 3, 2, 0, 3, 0, 3, 2, 0, 0, 2, 0, 0, 2, 2, 3, 1, 1, 2, 2, 2,
  0, 0, 2, 0,
];

export default [
  {
    id: 1,
    question: "Which is the highest mountain located in the continent Africa?",
    question_hi: "महाद्वीप अफ्रीका में स्थित सबसे ऊंचा पर्वत कौन सा है?",
    options: ["Kilimanjaro", "Mt. Logan", "Mt. Kenya", "Mt. Vishwanath"],
    options_hi: ["किलिमंजारो", "म्ट. लॉगन", "म्ट. केन्या", "म्ट. विश्वनाथ"],
    answer: "Kilimanjaro",
  },
  {
    id: 2,
    question: "Which is the largest ocean in the world?",
    question_hi: "दुनिया का सबसे बड़ा महासागर कौन सा है?",
    options: [
      "Mediterranean Sea",
      "Atlantic Ocean",
      "Indian Ocean",
      "Pacific Ocean",
    ],
    options_hi: [
      "भूमध्य सागर",
      "एटलांटिक महासागर",
      "हिंड महासागर",
      "प्रशांत महासागर",
    ],
    answer: "Pacific Ocean",
  },
  {
    id: 3,
    question: "What is the capital of Brazil?",
    question_hi: "ब्राजील की राजधानी क्या है?",
    options: ["Rio de Janeiro", "Sao Paulo", "Brasilia", "Saint Petersburg"],
    options_hi: ["रियो डी जनेरो", "साओ पाउलो", "ब्रासिलिया", "सैंट पीटर्सबर्ग"],
    answer: "Brasilia",
  },
  {
    id: 4,
    question: "In which country is the Nile River located?",
    question_hi: "नाइल नदी किस देश में स्थित है?",
    options: ["Egypt", "Sudan", "Nigeria", "Ethiopia"],
    options_hi: ["मिस्र", "सूडान", "नाइजीरिया", "इथियोपिया"],
    answer: "Egypt",
  },
  {
    id: 5,
    question: "Which is the highest peak in the Himalayan range?",
    question_hi: "हिमालय श्रृंग की सबसे ऊँची चोटी कौन सी है?",
    options: ["K2", "Kanchenjunga", "Mount Everest", "Mount Kilimanjaro"],
    options_hi: ["क2", "कांचनजंघा", "माउंट एवरेस्ट", "माउंट किलिमंजारो"],
    answer: "Mount Everest",
  },
  {
    id: 6,
    question: "Where is the world's largest town hall located?",
    question_hi: "विश्व की सबसे बड़ी टाउन हॉल कहाँ है?",
    options: ["Melbourne", "Sydney", "London", "New York"],
    options_hi: ["मेलबर्न", "सिडनी", "लंदन", "न्यूयॉर्क"],
    answer: "Sydney",
  },
  {
    id: 7,
    question: "What is the capital of Japan?",
    question_hi: "जापान की राजधानी क्या है?",
    options: ["Kyoto", "Osaka", "Nagoya", "Tokyo"],
    options_hi: ["क्योटो", "ओसाका", "नागोया", "टोक्यो"],
    answer: "Tokyo",
  },
  {
    id: 8,
    question: "What was the old name of New York City?",
    question_hi: "न्यूयॉर्क शहर के पुराने नाम क्या था?",
    options: ["New London", "New York", "New Amsterdam", "New Delhi"],
    options_hi: ["न्यू लंदन", "न्यू यार्क", "न्यू अम्स्टर्डम", "न्यू दिल्ली"],
    answer: "New Amsterdam",
  },
  {
    id: 9,
    question: "Which is the largest hot desert on Earth?",
    question_hi: "पृथ्वी का सबसे बड़ा मरुस्थल कौन है?",
    options: [
      "Sahara Desert",
      "Kalahari Desert",
      "Arabian Desert",
      "Thar Desert",
    ],
    options_hi: [
      "सहारा रेगिस्तान",
      "कालहारी रेगिस्तान",
      "अरबी रेगिस्तान",
      "थार रेगिस्तान",
    ],
    answer: "Sahara Desert",
  },
  {
    id: 10,
    question: "Which is the smallest of the five oceans?",
    question_hi: "पांच महासागरों में से कौन-सा सबसे छोटा है?",
    options: [
      "Indian Ocean",
      "Atlantic Ocean",
      "Pacific Ocean",
      "Arctic Ocean",
    ],
    options_hi: [
      "हिन्द महासागर",
      "एटलांटिक महासागर",
      "प्रशांत महासागर",
      "आर्कटिक महासागर",
    ],
    answer: "Arctic Ocean",
  },
  {
    id: 11,
    question: "What is the elevation of Mumbai?",
    question_hi: "मुम्बई की ऊचाई क्या है?",
    options: ["14 meters", "15 meters", "20 meters", "25 meters"],
    options_hi: ["14 मीटर", "15 मीटर", "20 मीटर", "25 मीटर"],
    answer: "14 meters",
  },
  {
    id: 12,
    question: "Which is the largest waterfall in the world?",
    question_hi: "विश्व का सबसे बड़ा जलधारा कौन सी है?",
    options: ["Victoria Falls", "Niagara Falls", "Iguazu Falls", "Angel Falls"],
    options_hi: [
      "विक्टोरिया फॉल्स",
      "नियागारा फॉल्स",
      "इगुआसू फॉल्स",
      "आंगेल फॉल्स",
    ],
    answer: "Angel Falls",
  },
  {
    id: 13,
    question: "Which is the longest river in the world?",
    question_hi: "दुनिया की सबसे लंबी नदी कौन सी है?",
    options: [
      "Yangtze River",
      "Nile River",
      "Amazon River",
      "Mississippi River",
    ],
    options_hi: ["यांग्ट्सी नदी", "नील नदी", "अमेज़न नदी", "मिसिसिपी नदी"],
    answer: "Amazon River",
  },
  {
    id: 14,
    question: "Which is the deepest lake on Earth?",
    question_hi: "पृथ्वी की सबसे गहरी झील कौन सी है?",
    options: ["Baikal Lake", "Great Bear Lake", "Crater Lake", "Victoria Lake"],
    options_hi: ["बैकाल झील", "ग्रेट बेयर झील", "क्राटर झील", "विक्टोरिया झील"],
    answer: "Baikal Lake",
  },
  {
    id: 15,
    question: "What is the capital of the United States of America?",
    question_hi: "संयुक्त राज्य अमेरिका की राजधानी क्या है?",
    options: ["Washington D.C.", "New York", "Los Angeles", "Chicago"],
    options_hi: ["वॉशिंगटन डीसी", "न्यूयॉर्क", "लॉस एंजिल्स", "चिकागो"],
    answer: "Washington D.C.",
  },
  {
    id: 16,
    question: "Which country shares the longest maritime border with India?",
    question_hi:
      "भारतीय समुद्री तट की सबसे लंबी समुद्री सीमा किस देश से होती है?",
    options: ["Sri Lanka", "Pakistan", "Bangladesh", "Myanmar"],
    options_hi: ["स्रीलंका", "पाकिस्तान", "बांग्लादेश", "म्यांमार"],
    answer: "Bangladesh",
  },
  {
    id: 17,
    question: "In which year was the Indian Air Force established?",
    question_hi: "भारतीय वायु सेना की स्थापना किस वर्ष हुई थी?",
    options: ["1932", "1947", "1950", "1951"],
    options_hi: ["1932", "1947", "1950", "1951"],
    answer: "1932",
  },
  {
    id: 18,
    question:
      "Between which cities was India's first railway line established?",
    question_hi: "भारत का पहला रेलमार्ग किस शहर के बीच बनाया गया था?",
    options: [
      "Mumbai - Pune",
      "Kolkata - Delhi",
      "Chennai - Bengaluru",
      "Delhi - Agra",
    ],
    options_hi: [
      "मुंबई - पुणे",
      "कोलकाता - दिल्ली",
      "चेन्नई - बेंगलुरु",
      "दिल्ली - आगरा",
    ],
    answer: "Mumbai - Pune",
  },
  {
    id: 19,
    question:
      "In which year was the Indian Air Force's environmental journey campaign launched?",
    question_hi:
      "भारतीय वायुसेना का पर्यावरण सफर अभियान किस वर्ष शुरू किया गया था?",
    options: ["2014", "2015", "2016", "2017"],
    options_hi: ["2014", "2015", "2016", "2017"],
    answer: "2016",
  },
  {
    id: 20,
    question: "Which is the northernmost point of a country?",
    question_hi: "किसी देश का सबसे उत्तरी बिंदु कौन सा है?",
    options: ["North America", "Greenland", "Russia", "Norway"],
    options_hi: ["उत्तर अमेरिका", "ग्रीनलैंड", "रूस", "नॉर्वे"],
    answer: "Russia",
  },
  {
    id: 21,
    question: "Which is the southernmost continent on Earth?",
    question_hi: "पृथ्वी का सबसे दक्षिणी महाद्वीप कौन सा है?",
    options: ["Australia", "Africa", "South America", "Antarctica"],
    options_hi: ["ऑस्ट्रेलिया", "अफ्रीका", "दक्षिण अमेरिका", "अंटार्कटिका"],
    answer: "Antarctica",
  },
  {
    id: 22,
    question: "Which country has the largest population?",
    question_hi: "किस देश में सबसे ज्यादा जनसंख्या है?",
    options: ["India", "China", "United States of America", "Indonesia"],
    options_hi: ["भारत", "चीन", "संयुक्त राज्य अमेरिका", "इंडोनेशिया"],
    answer: "China",
  },
  {
    id: 23,
    question: "Which is the largest continent in the world?",
    question_hi: "विश्व का सबसे बड़ा महाद्वीप कौन सा है?",
    options: ["Africa", "Asia", "Europe", "South America"],
    options_hi: ["अफ्रीका", "एशिया", "यूरोप", "दक्षिण अमेरिका"],
    answer: "Asia",
  },
  {
    id: 24,
    question: "NASA is the space agency of which country?",
    question_hi: "नासा किस देश की अंतरिक्ष एजेंसी है?",
    options: ["Russia", "India", "United States of America", "China"],
    options_hi: ["रूस", "भारत", "संयुक्त राज्य अमेरिका", "चीन"],
    answer: "United States of America",
  },
  {
    id: 25,
    question: "Euro currency is used in which continent?",
    question_hi: "यूरो मुद्रा किस महाद्वीप में उपयोग की जाती है?",
    options: ["Asia", "Africa", "Europe", "South America"],
    options_hi: ["एशिया", "अफ्रीका", "यूरोप", "दक्षिण अमेरिका"],
    answer: "Europe",
  },
  {
    id: 26,
    question: "Which is the largest country (area) in the world?",
    question_hi: "दुनिया का सबसे बड़ा देश (क्षेत्रफल) कौन सा है?",
    options: ["United States of America", "Canada", "Russia", "China"],
    options_hi: ["संयुक्त राज्य अमेरिका", "कनाडा", "रूस", "चीन"],
    answer: "Russia",
  },
  {
    id: 27,
    question: "Where is the headquarters of the United Nations located?",
    question_hi: "संयुक्त राष्ट्र का मुख्यालय कहाँ स्थित है?",
    options: ["New York", "Geneva", "London", "Paris"],
    options_hi: ["न्यूयॉर्क", "जेनेवा", "लंदन", "पेरिस"],
    answer: "New York",
  },
  {
    id: 28,
    question: "Which is the largest city (population) in the world?",
    question_hi: "दुनिया का सबसे बड़ा शहर (जनसंख्या) कौन सा है?",
    options: ["Tokyo", "Mumbai", "New York", "Shanghai"],
    options_hi: ["टोक्यो", "मुंबई", "न्यूयॉर्क", "शंघाई"],
    answer: "Tokyo",
  },
  {
    id: 29,
    question: "Which is the westernmost point of a country?",
    question_hi: "किसी देश का सबसे पश्चिमी बिंदु कौन सा है?",
    options: ["Europe", "Greenland", "Alaska", "Iceland"],
    options_hi: ["यूरोप", "ग्रीनलैंड", "अलास्का", "आइसलैंड"],
    answer: "Alaska",
  },
  {
    id: 30,
    question: "Which is the highest peak in the world?",
    question_hi: "विश्व का सबसे ऊँचा शिखर कौन सा है?",
    options: ["Mount Everest", "K2", "Kanchenjunga", "Lhotse"],
    options_hi: ["माउंट एवरेस्ट", "के2", "कांचनजंघा", "लोहत्से"],
    answer: "Mount Everest",
  },
  // {
  //   id: 31,
  //   question: "Which is the smallest continent?",
  //   question_hi: "कौन सा महाद्वीप सबसे छोटा है?",
  //   options: ["Africa", "Europe", "Australia", "South America"],
  //   options_hi: ["अफ्रीका", "यूरोप", "ऑस्ट्रेलिया", "दक्षिण अमेरिका"],
  //   answer: "Australia",
  // },
  // {
  //   id: 32,
  //   question: "Which is the largest volcano in the world?",
  //   question_hi: "दुनिया का सबसे बड़ा ज्वालामुखी कौन सा है?",
  //   options: ["Mauna Loa", "Mount Etna", "Mount Fuji", "Kilauea"],
  //   options_hi: ["मौनालोआ", "माउंट एटना", "माउंट फूजी", "किलाउआ"],
  //   answer: "Mauna Loa",
  // },
  // {
  //   id: 33,
  //   question: "In which year was India's independence declared?",
  //   question_hi: "भारत की स्वतंत्रता किस वर्ष में घोषित हुई थी?",
  //   options: ["1942", "1945", "1947", "1950"],
  //   options_hi: ["1942", "1945", "1947", "1950"],
  //   answer: "1947",
  // },
  // {
  //   id: 34,
  //   question: "Which is the upper house of the Indian Parliament?",
  //   question_hi: "भारतीय संसद का उच्च सदन कौन सा है?",
  //   options: ["Lok Sabha", "Rajya Sabha", "Vidhan Sabha", "Vidhan Parishad"],
  //   options_hi: ["लोकसभा", "राज्यसभा", "विधानसभा", "विधानपरिषद"],
  //   answer: "Rajya Sabha",
  // },
  // {
  //   id: 35,
  //   question: "Who was the chief architect of the Indian Constitution?",
  //   question_hi: "भारतीय संविधान का प्रमुख लेखक कौन था?",
  //   options: [
  //     "Mahatma Gandhi",
  //     "Jawaharlal Nehru",
  //     "B.R. Ambedkar",
  //     "Subhas Chandra Bose",
  //   ],
  //   options_hi: [
  //     "महात्मा गांधी",
  //     "जवाहरलाल नेहरू",
  //     "बी. आर. अंबेडकर",
  //     "सुभाष चंद्र बोस",
  //   ],
  //   answer: "B.R. Ambedkar",
  // },
  // {
  //   id: 36,
  //   question: "Who was the first President of India?",
  //   question_hi: "भारत के पहले राष्ट्रपति कौन थे?",
  //   options: [
  //     "Mahatma Gandhi",
  //     "Jawaharlal Nehru",
  //     "Subhas Chandra Bose",
  //     "Dr. Rajendra Prasad",
  //   ],
  //   options_hi: [
  //     "महात्मा गांधी",
  //     "जवाहरलाल नेहरू",
  //     "सुभाष चंद्र बोस",
  //     "डॉ. राजेंद्र प्रसाद",
  //   ],
  //   answer: "Dr. Rajendra Prasad",
  // },
  // {
  //   id: 37,
  //   question: "Which Indian state has the longest coastline?",
  //   question_hi: "किस भारतीय राज्य में सबसे बड़ा तटरेखा है?",
  //   options: ["Maharashtra", "Gujarat", "Tamil Nadu", "Andhra Pradesh"],
  //   options_hi: ["महाराष्ट्र", "गुजरात", "तमिलनाडु", "आंध्र प्रदेश"],
  //   answer: "Gujarat",
  // },
  // {
  //   id: 38,
  //   question: "Which is the longest river in India?",
  //   question_hi: "भारत की सबसे लंबी नदी कौन सी है?",
  //   options: ["Ganges", "Yamuna", "Brahmaputra", "Godavari"],
  //   options_hi: ["गंगा", "यमुना", "ब्रह्मपुत्र", "गोदावरी"],
  //   answer: "Ganges",
  // },
  // {
  //   id: 39,
  //   question: "Which is the national bird of India?",
  //   question_hi: "भारत का राष्ट्रीय पक्षी कौन सा है?",
  //   options: ["Pigeon", "Peacock", "Parrot", "Crow"],
  //   options_hi: ["कबूतर", "मोर", "तोता", "कौवा"],
  //   answer: "Peacock",
  // },
  // {
  //   id: 40,
  //   question: "Which is the national animal of India?",
  //   question_hi: "भारत का राष्ट्रीय पशु कौन सा है?",
  //   options: ["Elephant", "Tiger", "Lion", "Bear"],
  //   options_hi: ["हाथी", "बाघ", "शेर", "भालू"],
  //   answer: "Tiger",
  // },
  // {
  //   id: 41,
  //   question: "Which is the national sport of India?",
  //   question_hi: "भारत का राष्ट्रीय खेल कौन सा है?",
  //   options: ["Cricket", "Hockey", "Football", "Badminton"],
  //   options_hi: ["क्रिकेट", "हॉकी", "फुटबॉल", "बैडमिंटन"],
  //   answer: "Hockey",
  // },
  // {
  //   id: 42,
  //   question: "Which state in India has the highest population?",
  //   question_hi: "भारत के किस राज्य में सबसे ज्यादा जनसंख्या है?",
  //   options: ["Maharashtra", "Uttar Pradesh", "Bihar", "West Bengal"],
  //   options_hi: ["महाराष्ट्र", "उत्तर प्रदेश", "बिहार", "पश्चिम बंगाल"],
  //   answer: "Uttar Pradesh",
  // },
  // {
  //   id: 43,
  //   question: "Which is the largest state in India (area)?",
  //   question_hi: "भारत का सबसे बड़ा राज्य (क्षेत्रफल) कौन सा है?",
  //   options: ["Maharashtra", "Uttar Pradesh", "Madhya Pradesh", "Rajasthan"],
  //   options_hi: ["महाराष्ट्र", "उत्तर प्रदेश", "मध्य प्रदेश", "राजस्थान"],
  //   answer: "Rajasthan",
  // },
  // {
  //   id: 44,
  //   question: "Which is the longest lake in India?",
  //   question_hi: "भारत की सबसे लंबी झील कौन सी है?",
  //   options: ["Chilka Lake", "Vembanad Lake (Kerala)", "Loktak Lake", "Sambhar Lake"],
  //   options_hi: ["चिल्का झील", "वेम्बनाड झील", "लोकटक झील", "सांभर झील"],
  //   answer: "Vembanad Lake (Kerala)",
  // },
  // {
  //   id: 45,
  //   question: "Which state in India has the highest number of tigers?",
  //   question_hi: "भारत के किस राज्य में सबसे ज्यादा बाघ हैं?",
  //   options: ["Madhya Pradesh", "Karnataka", "Uttar Pradesh", "Maharashtra"],
  //   options_hi: ["मध्य प्रदेश", "कर्नाटक", "उत्तर प्रदेश", "महाराष्ट्र"],
  //   answer: "Madhya Pradesh",
  // },
  // {
  //   id: 46,
  //   question: "Which is the national tree of India?",
  //   question_hi: "भारत का राष्ट्रीय वृक्ष कौन सा है?",
  //   options: ["Neem", "Babul", "Peepal", "Banyan"],
  //   options_hi: ["नीम", "बाबूल", "पीपल", "बरगद "],
  //   answer: "Banyan",
  // },
  // {
  //   id: 47,
  //   question: "Which is the national flower of India?",
  //   question_hi: "भारत का राष्ट्रीय फूल कौन सा है?",
  //   options: ["Rose", "Lotus", "Marigold", "Sunflower"],
  //   options_hi: ["गुलाब", "कमल", "गेंदे का फूल", "सूरजमुखी"],
  //   answer: "Lotus",
  // },
  // {
  //   id: 48,
  //   question: "Which is the national fruit of India?",
  //   question_hi: "भारत का राष्ट्रीय फल कौन सा है?",
  //   options: ["Apple", "Banana", "Mango", "Orange"],
  //   options_hi: ["सेब", "केला", "आम", "संतरा"],
  //   answer: "Mango",
  // },
  // {
  //   id: 49,
  //   question: "Which is the national song of India?",
  //   question_hi: "भारत का राष्ट्रीय गीत कौन सा है?",
  //   options: [
  //     "Jana Gana Mana",
  //     "Vande Mataram",
  //     "Saare Jahan Se Achha",
  //     "Jai Hind",
  //   ],
  //   options_hi: ["जन गण मन", "वंदे मातरम", "सारे जहाँ से अच्छा", "जय हिंद"],
  //   answer: "Vande Mataram",
  // },
  // {
  //   id: 50,
  //   question: "Which is the national anthem of India?",
  //   question_hi: "भारत का राष्ट्रीय गान कौन सा है?",
  //   options: [
  //     "Jana Gana Mana",
  //     "Vande Mataram",
  //     "Saare Jahan Se Achha",
  //     "Jai Hind",
  //   ],
  //   options_hi: ["जन गण मन", "वंदे मातरम", "सारे जहाँ से अच्छा", "जय हिंद"],
  //   answer: "Jana Gana Mana",
  // },
  // {
  //   id: 51,
  //   question: "What is the SI unit of force?",
  //   question_hi: "बल की SI इकाई क्या है?",
  //   options: ["Newton", "Joule", "Watt", "Pascal"],
  //   options_hi: ["न्यूटन", "जूल", "वॉट", "पास्कल"],
  //   answer: "Newton",
  // },
  // {
  //   id: 52,
  //   question: "Which of the following is a noble gas?",
  //   question_hi: "निम्नलिखित में से कौन सा एक शांत गैस है?",
  //   options: ["Oxygen", "Neon", "Hydrogen", "Nitrogen"],
  //   options_hi: ["ऑक्सीजन", "नीओन", "हाइड्रोजन", "नाइट्रोजन"],
  //   answer: "Neon",
  // },
  // {
  //   id: 53,
  //   question: "What is the powerhouse of the cell?",
  //   question_hi: "कोशिका का पावरहाउस क्या होता है?",
  //   options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"],
  //   options_hi: ["न्यूक्लियस", "राइबोसोम", "माइटोकंड्रिया", "गोल्गी यंत्र"],
  //   answer: "Mitochondria",
  // },
  // {
  //   id: 54,
  //   question: "What does the atomic number of an element represent?",
  //   question_hi: "एक तत्व की परमाणु संख्या क्या प्रतिनिधित्व करती है?",
  //   options: [
  //     "Number of neutrons",
  //     "Number of protons",
  //     "Number of electrons",
  //     "Atomic mass",
  //   ],
  //   options_hi: [
  //     "न्यूट्रॉनों की संख्या",
  //     "प्रोटॉनों की संख्या",
  //     "इलेक्ट्रॉनों की संख्या",
  //     "परमाणु मास",
  //   ],
  //   answer: "Number of protons",
  // },
  // {
  //   id: 55,
  //   question:
  //     "Which law of motion states 'for every action, there is an equal and opposite reaction'?",
  //   question_hi:
  //     "गति का कौन सा नियम कहता है 'हर क्रिया के लिए, बराबर और विपरीत प्रतिक्रिया होती है'?",
  //   options: ["First law", "Second law", "Third law", "Fourth law"],
  //   options_hi: ["पहला नियम", "दूसरा नियम", "तीसरा नियम", "चौथा नियम"],
  //   answer: "Third law",
  // },
  // {
  //   id: 56,
  //   question: "What is the chemical formula of water?",
  //   question_hi: "पानी का रासायनिक सूत्र क्या है?",
  //   options: ["H2O2", "CO2", "H2O", "CH4"],
  //   options_hi: ["H2O2", "CO2", "H2O", "CH4"],
  //   answer: "H2O",
  // },
  // {
  //   id: 57,
  //   question: "Which organelle is responsible for protein synthesis?",
  //   question_hi: "प्रोटीन संश्लेषण के लिए कौन सा अणुकोशिका जिम्मेदार है?",
  //   options: ["Nucleus", "Mitochondria", "Ribosome", "Endoplasmic reticulum"],
  //   options_hi: ["न्यूक्लियस", "माइटोकंड्रिया", "राइबोसोम", "अंतर्भ्रांत पैच"],
  //   answer: "Ribosome",
  // },
  // {
  //   id: 58,
  //   question: "What is the formula for acceleration?",
  //   question_hi: "त्वरण के लिए सूत्र क्या है?",
  //   options: ["v = u + at", "a = (v - u) / t", "s = ut + 0.5at^2", "F = ma"],
  //   options_hi: ["v = u + at", "a = (v - u) / t", "s = ut + 0.5at^2", "F = ma"],
  //   answer: "a = (v - u) / t",
  // },
  // {
  //   id: 59,
  //   question: "Which gas is most abundant in Earth's atmosphere?",
  //   question_hi: "पृथ्वी के वायुमंडल में सबसे अधिक मात्रा में कौन सा गैस है?",
  //   options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"],
  //   options_hi: ["नाइट्रोजन", "ऑक्सीजन", "कार्बन डाइऑक्साइड", "आर्गन"],
  //   answer: "Nitrogen",
  // },
  // {
  //   id: 60,
  //   question:
  //     "Which scientist proposed the theory of evolution by natural selection?",
  //   question_hi:
  //     "कौन सा वैज्ञानिक प्राकृतिक चयन द्वारा उत्तरण की सिद्धांत प्रस्तुत किया था?",
  //   options: [
  //     "Charles Darwin",
  //     "Gregor Mendel",
  //     "Louis Pasteur",
  //     "Albert Einstein",
  //   ],
  //   options_hi: [
  //     "चार्ल्स डार्विन",
  //     "ग्रेगर मेंडल",
  //     "लुई पास्टर",
  //     "अल्बर्ट आइंस्टीन",
  //   ],
  //   answer: "Charles Darwin",
  // },
  // {
  //   id: 61,
  //   question: "What is the unit of electric current?",
  //   question_hi: "विद्युत धारा की SI इकाई क्या है?",
  //   options: ["Volt", "Ampere", "Ohm", "Watt"],
  //   options_hi: ["वोल्ट", "एम्पियर", "ओहम", "वॉट"],
  //   answer: "Ampere",
  // },
  // {
  //   id: 62,
  //   question: "What is the chemical symbol for iron?",
  //   question_hi: "लोहे का रासायनिक प्रतीक क्या है?",
  //   options: ["Ir", "Fe", "In", "Io"],
  //   options_hi: ["Ir", "Fe", "In", "Io"],
  //   answer: "Fe",
  // },
  // {
  //   id: 63,
  //   question:
  //     "Which blood vessel carries oxygenated blood away from the heart?",
  //   question_hi:
  //     "कौन सी रक्तसंवाहिका हृदय से ऑक्सीजन युक्त रक्त को दूर ले जाती है?",
  //   options: ["Vein", "Artery", "Capillary", "Aorta"],
  //   options_hi: ["शिरा", "धमनी", "धमनी", "अर्टरी"],
  //   answer: "Artery",
  // },
  // {
  //   id: 64,
  //   question: "What is the formula for momentum?",
  //   question_hi: "गतिमान के लिए सूत्र क्या है?",
  //   options: ["p = mv", "F = ma", "P = VI", "E = mc^2"],
  //   options_hi: ["p = mv", "F = ma", "P = VI", "E = mc^2"],
  //   answer: "p = mv",
  // },
  // {
  //   id: 65,
  //   question: "Which gas is known as laughing gas?",
  //   question_hi: "हंसी गैस के रूप में जाना जाने वाला कौन सा गैस है?",
  //   options: ["Carbon dioxide", "Methane", "Nitrous oxide", "Sulfur dioxide"],
  //   options_hi: [
  //     "कार्बन डाइऑक्साइड",
  //     "मीथेन",
  //     "नाइट्रस ऑक्साइड",
  //     "सल्फर डाइऑक्साइड",
  //   ],
  //   answer: "Nitrous oxide",
  // },
  // {
  //   id: 66,
  //   question: "What is the largest organ in the human body?",
  //   question_hi: "मानव शरीर में सबसे बड़ा अंग कौन सा है?",
  //   options: ["Brain", "Skin", "Heart", "Liver"],
  //   options_hi: ["मस्तिष्क", "त्वचा", "दिल", "जिगर"],
  //   answer: "Skin",
  // },
  // {
  //   id: 67,
  //   question: "What is the unit of electric resistance?",
  //   question_hi: "विद्युत प्रतिरोध की SI इकाई क्या है?",
  //   options: ["Volt", "Ampere", "Ohm", "Watt"],
  //   options_hi: ["वोल्ट", "एम्पियर", "ओहम", "वॉट"],
  //   answer: "Ohm",
  // },
  // {
  //   id: 68,
  //   question: "Which gas is produced during photosynthesis?",
  //   question_hi: "क्लोरोफिल प्रक्रिया के दौरान कौन सा गैस उत्पन्न होता है?",
  //   options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"],
  //   options_hi: ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "हाइड्रोजन"],
  //   answer: "Oxygen",
  // },
  // {
  //   id: 69,
  //   question:
  //     "Which law of thermodynamics states that energy cannot be created or destroyed, only transformed?",
  //   question_hi:
  //     "ऊष्मागतिकी का कौन सा नियम कहता है कि ऊर्जा को सिर्फ रूपांतरित किया जा सकता है, न कि उत्पन्न किया या नष्ट किया जा सकता है?",
  //   options: ["First law", "Second law", "Third law", "Zeroth law"],
  //   options_hi: ["प्रथम नियम", "द्वितीय नियम", "तृतीय नियम", "शून्य वाला नियम"],
  //   answer: "First law",
  // },
  // {
  //   id: 70,
  //   question: "Which acid is present in lemon?",
  //   question_hi: "नींबू में कौन सा अम्ल मौजूद है?",
  //   options: [
  //     "Acetic acid",
  //     "Citric acid",
  //     "Sulfuric acid",
  //     "Hydrochloric acid",
  //   ],
  //   options_hi: [
  //     "सिट्रिक अम्ल",
  //     "सिट्रिक अम्ल",
  //     "सल्फ्यूरिक अम्ल",
  //     "हाइड्रोक्लोरिक अम्ल",
  //   ],
  //   answer: "Citric acid",
  // },
  // {
  //   id: 71,
  //   question: "What is the powerhouse of a plant cell?",
  //   question_hi: "एक पौधे की कोशिका का पावरहाउस क्या होता है?",
  //   options: ["Chloroplast", "Vacuole", "Nucleus", "Mitochondria"],
  //   options_hi: ["क्लोरोप्लास्ट", "वैक्यूल", "न्यूक्लियस", "माइटोकंड्रिया"],
  //   answer: "Chloroplast",
  // },
  // {
  //   id: 72,
  //   question: "What is the unit of electric power?",
  //   question_hi: "विद्युत शक्ति की SI इकाई क्या है?",
  //   options: ["Volt", "Ampere", "Ohm", "Watt"],
  //   options_hi: ["वोल्ट", "एम्पियर", "ओहम", "वॉट"],
  //   answer: "Watt",
  // },
  // {
  //   id: 73,
  //   question: "What is the chemical symbol for gold?",
  //   question_hi: "सोने का रासायनिक प्रतीक क्या है?",
  //   options: ["Au", "Ag", "Pb", "Hg"],
  //   options_hi: ["Au", "Ag", "Pb", "Hg"],
  //   answer: "Au",
  // },
  // {
  //   id: 74,
  //   question: "Which blood vessel carries deoxygenated blood to the heart?",
  //   question_hi: "कौन सी रक्तसंवाहिका अस्वस्थ रक्त को हृदय की ओर ले जाती है?",
  //   options: ["Vein", "Artery", "Capillary", "Aorta"],
  //   options_hi: ["शिरा", "धमनी", "धमनी", "अर्टरी"],
  //   answer: "Vein",
  // },
  // {
  //   id: 75,
  //   question: "What is the formula for density?",
  //   question_hi: "घनत्व के लिए सूत्र क्या है?",
  //   options: ["D = m/v", "P = VI", "F = ma", "E = mc^2"],
  //   options_hi: ["D = m/v", "P = VI", "F = ma", "E = mc^2"],
  //   answer: "D = m/v",
  // },
  // {
  //   id: 76,
  //   question: "Which gas is used in balloons for flying?",
  //   question_hi: "उड़ने के बेलून में कौन सा गैस उपयोग किया जाता है?",
  //   options: ["Oxygen", "Helium", "Nitrogen", "Hydrogen"],
  //   options_hi: ["ऑक्सीजन", "हीलियम", "नाइट्रोजन", "हाइड्रोजन"],
  //   answer: "Helium",
  // },
  // {
  //   id: 77,
  //   question: "What is the chemical formula of table salt?",
  //   question_hi: "मीज से नमक का रासायनिक सूत्र क्या है?",
  //   options: ["NaCl", "H2O", "CO2", "O2"],
  //   options_hi: ["NaCl", "H2O", "CO2", "O2"],
  //   answer: "NaCl",
  // },
  // {
  //   id: 78,
  //   question: "Which part of the human body contains enamel?",
  //   question_hi: "मानव शरीर का कौन सा भाग आवरण सम्मिलित है?",
  //   options: ["Teeth", "Skin", "Bones", "Muscles"],
  //   options_hi: ["दांत", "त्वचा", "हड्डियां", "मांसपेशियां"],
  //   answer: "Teeth",
  // },
  // {
  //   id: 79,
  //   question: "What is the chemical symbol for silver?",
  //   question_hi: "चांदी का रासायनिक प्रतीक क्या है?",
  //   options: ["Au", "Ag", "Pb", "Hg"],
  //   options_hi: ["Au", "Ag", "Pb", "Hg"],
  //   answer: "Ag",
  // },
  // {
  //   id: 80,
  //   question: "Which gas is known as the 'universal solvent'?",
  //   question_hi: "कौन सा गैस 'विश्व-विलयक' के रूप में जाना जाता है?",
  //   options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Water vapor"],
  //   options_hi: ["ऑक्सीजन", "हाइड्रोजन", "कार्बन डाइऑक्साइड", "पानी का बाष्प"],
  //   answer: "Water vapor",
  // },
  // {
  //   id: 81,
  //   question: "Which part of the human eye contains photoreceptor cells?",
  //   question_hi:
  //     "मानव आँख का कौन सा हिस्सा प्रकाशरेक्तापक कोशिकाएँ सम्मिलित है?",
  //   options: ["Cornea", "Retina", "Iris", "Lens"],
  //   options_hi: ["कोरिया", "नेत्रपट", "आईरिस", "लेंस"],
  //   answer: "Retina",
  // },
  // {
  //   id: 82,
  //   question: "What is the formula for electric current?",
  //   question_hi: "विद्युत धारा के लिए सूत्र क्या है?",
  //   options: ["I = Q/t", "P = VI", "F = ma", "E = mc^2"],
  //   options_hi: ["I = Q/t", "P = VI", "F = ma", "E = mc^2"],
  //   answer: "I = Q/t",
  // },
  // {
  //   id: 83,
  //   question: "Which gas is responsible for the greenhouse effect?",
  //   question_hi: "हरितागृह प्रभाव के लिए कौन सा गैस जिम्मेदार है?",
  //   options: ["Oxygen", "Methane", "Carbon dioxide", "Nitrogen"],
  //   options_hi: ["ऑक्सीजन", "मीथेन", "कार्बन डाइऑक्साइड", "नाइट्रोजन"],
  //   answer: "Carbon dioxide",
  // },
  // {
  //   id: 84,
  //   question: "Which part of a plant cell stores water and nutrients?",
  //   question_hi:
  //     "एक पौधे की कोशिका का कौन सा भाग पानी और पोषक तत्वों को संग्रहित करता है?",
  //   options: ["Chloroplast", "Vacuole", "Nucleus", "Mitochondria"],
  //   options_hi: ["क्लोरोप्लास्ट", "वैक्यूल", "न्यूक्लियस", "माइटोकंड्रिया"],
  //   answer: "Vacuole",
  // },
  // {
  //   id: 85,
  //   question: "What is the unit of electric capacitance?",
  //   question_hi: "विद्युत क्षमता की SI इकाई क्या है?",
  //   options: ["Farad", "Tesla", "Ohm", "Watt"],
  //   options_hi: ["फैरड", "टेस्ला", "ओहम", "वॉट"],
  //   answer: "Farad",
  // },
  // {
  //   id: 86,
  //   question: "Which gas is commonly used in fire extinguishers?",
  //   question_hi: "अग्निशामक में आमतौर पर कौन सा गैस प्रयुक्त होता है?",
  //   options: ["Oxygen", "Carbon monoxide", "Nitrogen", "Carbon dioxide"],
  //   options_hi: [
  //     "ऑक्सीजन",
  //     "कार्बन मोनोक्साइड",
  //     "नाइट्रोजन",
  //     "कार्बन डाइऑक्साइड",
  //   ],
  //   answer: "Carbon dioxide",
  // },
  // {
  //   id: 87,
  //   question: "Which blood vessel connects arteries and veins?",
  //   question_hi: "कौन सी रक्तसंवाहिका धमनियों और धमनियों को जोड़ती है?",
  //   options: ["Capillary", "Vena cava", "Pulmonary artery", "Aorta"],
  //   options_hi: ["कैपिलेरी", "वीना केवा", "पल्मोनरी आर्टरी", "आर्टेरी"],
  //   answer: "Capillary",
  // },
  // {
  //   id: 88,
  //   question: "What is the unit of magnetic field strength?",
  //   question_hi: "चुम्बकीय क्षेत्र की SI इकाई क्या है?",
  //   options: ["Tesla", "Weber", "Ohm", "Hertz"],
  //   options_hi: ["टेस्ला", "वेबर", "ओहम", "हर्ट्ज़"],
  //   answer: "Tesla",
  // },
  // {
  //   id: 89,
  //   question: "Which gas is produced during respiration?",
  //   question_hi: "श्वसन के दौरान कौन सा गैस उत्पन्न होता है?",
  //   options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"],
  //   options_hi: ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "हाइड्रोजन"],
  //   answer: "Carbon dioxide",
  // },
  // {
  //   id: 90,
  //   question: "What is the SI unit of temperature?",
  //   question_hi: "तापमान की SI इकाई क्या है?",
  //   options: ["Celsius", "Kelvin", "Fahrenheit", "Rankine"],
  //   options_hi: ["सेल्सियस", "केल्विन", "फ़ारेनहाइट", "रैंकिन"],
  //   answer: "Kelvin",
  // },
  // {
  //   id: 91,
  //   question: "Which type of radiation is associated with skin cancer?",
  //   question_hi: "किस प्रकार की विकिरण त्वचा के कैंसर से जुड़ा होता है?",
  //   options: ["Gamma", "Alpha", "Beta", "X-ray"],
  //   options_hi: ["गामा", "अल्फा", "बीटा", "एक्स-रे"],
  //   answer: "Gamma",
  // },
  // {
  //   id: 92,
  //   question: "Which blood cells are responsible for clotting?",
  //   question_hi: "संघनी के लिए जिम्मेदार कौन सी रक्त कोशिकाएं होती हैं?",
  //   options: ["Red blood cells", "White blood cells", "Platelets", "Plasma"],
  //   options_hi: [
  //     "लाल रक्त कोशिकाएं",
  //     "सफेद रक्त कोशिकाएं",
  //     "प्लेटलेट्स",
  //     "प्लाज्मा",
  //   ],
  //   answer: "Platelets",
  // },
  // {
  //   id: 93,
  //   question: "What is the chemical symbol for lead?",
  //   question_hi: "सीस का रासायनिक प्रतीक क्या है?",
  //   options: ["Au", "Ag", "Pb", "Hg"],
  //   options_hi: ["Au", "Ag", "Pb", "Hg"],
  //   answer: "Pb",
  // },
  // {
  //   id: 94,
  //   question: "Which part of the plant is responsible for photosynthesis?",
  //   question_hi:
  //     "कौन सा भाग पौधे के लिए क्लोरोफिल प्रक्रिया के लिए जिम्मेदार होता है?",
  //   options: ["Roots", "Leaves", "Stem", "Flowers"],
  //   options_hi: ["जड़ें", "पत्तियां", "तना", "फूल"],
  //   answer: "Leaves",
  // },
  // {
  //   id: 95,
  //   question: "Which acid is present in vinegar?",
  //   question_hi: "सिरके में कौन सा अम्ल मौजूद है?",
  //   options: [
  //     "Acetic acid",
  //     "Citric acid",
  //     "Sulfuric acid",
  //     "Hydrochloric acid",
  //   ],
  //   options_hi: [
  //     "ऐसिटिक अम्ल",
  //     "सिट्रिक अम्ल",
  //     "सल्फ्यूरिक अम्ल",
  //     "हाइड्रोक्लोरिक अम्ल",
  //   ],
  //   answer: "Acetic acid",
  // },
  // {
  //   id: 96,
  //   question: "What is the SI unit of energy?",
  //   question_hi: "ऊर्जा की SI इकाई क्या है?",
  //   options: ["Joule", "Watt", "Volt", "Ampere"],
  //   options_hi: ["जूल", "वॉट", "वोल्ट", "एम्पियर"],
  //   answer: "Joule",
  // },
  // {
  //   id: 97,
  //   question: "Which type of energy does an unlit match have?",
  //   question_hi: "एक अंधेरे माचिस किस प्रकार की ऊर्जा रखती है?",
  //   options: ["Chemical", "Nuclear", "Mechanical", "Electrical"],
  //   options_hi: ["रासायनिक", "परमाणु", "यांत्रिक", "इलेक्ट्रिकल"],
  //   answer: "Chemical",
  // },
  // {
  //   id: 98,
  //   question: "Which acid is present in lemons and other citrus fruits?",
  //   question_hi: "नींबू और अन्य साइट्रस फलों में कौन सा अम्ल होता है?",
  //   options: [
  //     "Acetic acid",
  //     "Citric acid",
  //     "Sulfuric acid",
  //     "Hydrochloric acid",
  //   ],
  //   options_hi: [
  //     "ऐसिटिक अम्ल",
  //     "सिट्रिक अम्ल",
  //     "सल्फ्यूरिक अम्ल",
  //     "हाइड्रोक्लोरिक अम्ल",
  //   ],
  //   answer: "Citric acid",
  // },
  // {
  //   id: 99,
  //   question: "What is the unit of wavelength?",
  //   question_hi: "अवधि की SI इकाई क्या है?",
  //   options: ["Meter", "Second", "Hertz", "Meter"],
  //   options_hi: ["मीटर", "सेकंड", "हर्ट्ज़", "मीटर"],
  //   answer: "Meter",
  // },
  // {
  //   id: 100,
  //   question: "Which acid is present in tomatoes?",
  //   question_hi: "टमाटर में कौन सा अम्ल मौजूद है?",
  //   options: [
  //     "Acetic acid",
  //     "Citric acid",
  //     "Sulfuric acid",
  //     "Hydrochloric acid",
  //   ],
  //   options_hi: [
  //     "ऐसिटिक अम्ल",
  //     "सिट्रिक अम्ल",
  //     "सल्फ्यूरिक अम्ल",
  //     "हाइड्रोक्लोरिक अम्ल",
  //   ],
  //   answer: "Citric acid",
  // },
];
